SELECT B.AUTHOR_ID, C.AUTHOR_NAME, B.CATEGORY, SUM((SALES * PRICE)) AS TOTAL_SALES

FROM BOOK_SALES A
JOIN BOOK B ON A.BOOK_ID = B.BOOK_ID
JOIN AUTHOR C ON B.AUTHOR_ID = C.AUTHOR_ID

WHERE YEAR(A.SALES_DATE) = 2022 AND MONTH(A.SALES_DATE) = 1
GROUP BY CATEGORY, AUTHOR_ID
ORDER BY B.AUTHOR_ID, CATEGORY DESC