-- 코드를 입력하세요
SELECT r.REST_ID, REST_NAME, FOOD_TYPE, FAVORITES, ADDRESS, ROUND(AVG(REVIEW_SCORE), 2) AS SCORE
FROM REST_INFO i JOIN REST_REVIEW r ON i.REST_ID = r.REST_ID
GROUP BY i.REST_ID
HAVING ADDRESS LIKE '서울%'
ORDER BY SCORE DESC, FAVORITES DESC