-- 코드를 작성해주세요
# SELECT COUNT(*) AS FISH_COUNT, FISH_NAME
# FROM FISH_NAME_INFO A JOIN (
#     SELECT FISH_TYPE FROM FISH_INFO GROUP BY FISH_TYPE
# ) B
# ON A.FISH_TYPE = B.FISH_TYPE
# ORDER BY FISH_COUNT DESC


SELECT COUNT(*) FISH_COUNT, A.FISH_NAME
FROM FISH_NAME_INFO A JOIN FISH_INFO B
ON A.FISH_TYPE = B.FISH_TYPE
GROUP BY A.FISH_TYPE, A.FISH_NAME
ORDER BY FISH_COUNT DESC