-- 코드를 작성해주세요
SELECT YEAR(a.DIFFERENTIATION_DATE) AS YEAR, ABS(MAX_SIZE - a.SIZE_OF_COLONY) AS YEAR_DEV, a.ID
FROM ECOLI_DATA a LEFT JOIN (
    SELECT YEAR(DIFFERENTIATION_DATE) AS YEAR, MAX(SIZE_OF_COLONY) AS MAX_SIZE
    FROM ECOLI_DATA
    GROUP BY YEAR(DIFFERENTIATION_DATE)
) b
ON YEAR(a.DIFFERENTIATION_DATE) = b.YEAR
ORDER BY YEAR, YEAR_DEV