-- 코드를 작성해주세요

SELECT B.SCORE, A.EMP_NO, EMP_NAME, POSITION, EMAIL
FROM HR_EMPLOYEES A JOIN (
    SELECT EMP_NO, SUM(SCORE) SCORE
    FROM HR_GRADE
    GROUP BY YEAR, EMP_NO
    HAVING YEAR = '2022'
) B
ON A.EMP_NO = B.EMP_NO
ORDER BY B.SCORE DESC
LIMIT 1
