-- 코드를 입력하세요
SELECT CATEGORY, SUM(B.COUNT) AS TOTAL_SALES
FROM BOOK A
    JOIN (
        SELECT BOOK_ID, SUM(SALES) COUNT
        FROM BOOK_SALES
        WHERE YEAR(SALES_DATE) = 2022 AND MONTH(SALES_DATE) = 1
        GROUP BY BOOK_ID
    ) B
ON A.BOOK_ID = B.BOOK_ID
GROUP BY CATEGORY
ORDER BY CATEGORY